### ISSUE TITLE
Finished, but unsure if the project works here

### ISSUE THREAD

**Issue by Luunche** [JCS-Computer-Science/project-credit-Luunche#1]
When I was cloning the repository to submit I was unable to check the project (the page was blank) even though the files are the exact same. Hopefully, it was just being weird and works perfectly fine

**Comment by JoeTodes** [comment]
fixed a couple file name errors that was causing it to not work, looks like your src folder accidentally got renamed to sfx, which broke some stuff. Working now, thanks!
